kind: blueprint
clouds:
- aws: eu-west-1
applications:
- s3reader:
    input_values:
    - INSTANCETYPE: $INSTANCETYPE
    - bucket: $bucket
    - AWS_ACCESS_KEY_ID: AKIAIO4JQW6LPGSTWLZA
    - AWS_SECRET_ACCESS_KEY: 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
    - AWS_DEFAULT_REGION: eu-west-1
    depends_on:
    - s3store_test
services:
- s3store_test:
    input_values:
    - bucket: $bucket
    - SANDBOX_ID: $SandboxId
    - SANDBOX_DNS: $PublicAddress
spec_version: 1
environmentType: sandbox
artifacts:
- s3reader: 's3reader/s3reader.py'
inputs:
- INSTANCETYPE: t3.small,t3.medium,c5.large,m5.large,m4.large
- bucket: quali-s3store
inputs:
- INSTANCETYPE: t3.small,t3.medium,c5.large,m5.large,m4.large
- AZURE_VM_SIZE: Basic_A1
- bucket
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- AWS_DEFAULT_REGION
configuration:
  healthcheck:
    script: healthcheck.sh
    timeout: 1000
  initialization:
    script: init.sh
  start:
    script: start.sh
source:
  image:
    docker_image:
    - name: quali/ubuntu
      tag: python36
    ami:
    - id: ami-0fbb0597fc7444183
      region: eu-west-1
      username: ubuntu
    azure_image:
    - urn: Canonical:UbuntuServer:16.04-LTS:latest
  os_type: linux
infrastructure:
  compute:
    spec:
      aws:
        instance_type: $INSTANCETYPE
      azure:
        vm_size: $AZURE_VM_SIZE
  connectivity:
    external:
    - port_info:
        port: 3000
        path: ''
debugging:
  connection_protocol: SSH
kind: application
spec_version: 1
